const fakeAdverts = [
  {
    _id: 'd3kf7c0d',
    address: { city: 'г. Москва', region: 'Старый Зыковский проезд, 4' },
    latitude: 55,
    longitude: 55,
    rent: ['one', 'two'],
    pay: 28000,
    pledge: 28000,
    tenants: 1,
    text: 'data.text',
    whom: { company: true },
    tags: { child: true },
    name: 'Максим',
    createdAt: new Date(),
  },
  {
    _id: 'eoem7p2b',
    address: { city: 'г. Москва', region: 'Складочная улица, 1с5' },
    latitude: 55,
    longitude: 55,
    rent: ['one'],
    pay: 24000,
    pledge: '',
    tenants: 1,
    text: 'data.text',
    whom: { female: true },
    tags: { smoke: true },
    name: 'Алексей',
    createdAt: new Date(),
  },
  {
    _id: 'n071ml80',
    address: { city: 'г. Москва', region: 'улица Архитектора Власова, 19к4' },
    latitude: 55,
    longitude: 55,
    rent: ['room', 'partOfHouse'],
    pay: 24000,
    pledge: 20000,
    tenants: 1,
    text: 'data.text',
    whom: {
      female: true,
      couple: true,
    },
    tags: { alcohol: true },
    name: 'Людмила',
    createdAt: new Date(),
  },
  {
    _id: 'cb072mn1',
    address: { city: 'г. Москва', region: 'улица Цюрупы, 12к3' },
    latitude: 55,
    longitude: 55,
    rent: ['two', 'three'],
    pay: 60000,
    pledge: 30000,
    tenants: 3,
    text: 'data.text',
    whom: { female: true },
    tags: { smoke: true },
    name: 'Иван',
    createdAt: new Date(),
  },
  {
    _id: 'ph6o4e3j',
    address: { city: 'г. Москва', region: 'улица Цюрупы, 12к3' },
    latitude: 55,
    longitude: 55,
    rent: ['room', 'one'],
    pay: 26000,
    pledge: '',
    tenants: 2,
    text: 'data.text',
    whom: {
      female: true,
      male: true,
    },
    tags: { animal: true },
    name: 'Александр',
    createdAt: new Date(),
  },
  {
    _id: '5pbfd22e',
    address: { city: 'г. Москва', region: 'Ставропольская улица, 8к2' },
    latitude: 55,
    longitude: 55,
    rent: ['room', 'one'],
    pay: 25000,
    pledge: 25000,
    tenants: 1,
    text: 'data.text',
    whom: {
      female: true,
      male: true,
    },
    tags: { animal: true },
    name: 'Валентин',
    createdAt: new Date(),
  },
  {
    _id: '0hm2805p',
    address: { city: 'г. Москва', region: 'Ставропольская улица, 8к2' },
    latitude: 55,
    longitude: 55,
    rent: ['one', 'two'],
    pay: 29000,
    pledge: 29000,
    tenants: 2,
    text: 'data.text',
    whom: { female: true },
    tags: { child: true },
    name: 'Инна',
    createdAt: new Date(),
  },
  {
    _id: 'k7an8ila',
    address: { city: 'г. Москва', region: 'Снайперская улица, 3' },
    latitude: 55,
    longitude: 55,
    rent: ['one', 'two'],
    pay: 32000,
    pledge: 32000,
    tenants: 2,
    text: 'data.text',
    whom: { female: true },
    tags: { animal: true },
    name: 'Евдаким',
    createdAt: new Date(),
  },
  {
    _id: 'a1n4mopk',
    address: { city: 'г. Москва', region: 'улица Молдагуловой, 14' },
    latitude: 55,
    longitude: 55,
    rent: ['one'],
    pay: 38000,
    pledge: 38000,
    tenants: 2,
    text: 'data.text',
    whom: {
      female: true,
      couple: true,
    },
    tags: { smoke: true },
    name: 'Анастасия',
    createdAt: new Date(),
  },
]

const fakeUsers = [{
  name: 'Алексей',
  favorite_adverts: '',
  createdAt: new Date(),
}]

module.exports = {
  fakeAdverts,
  fakeUsers,
}
